[package]
name = "mesh-cni-vxlan-controller"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]
ahash = { workspace = true }
futures = { workspace = true }
ipnetwork = { workspace = true }
k8s-openapi = { workspace = true }
kube = { workspace = true }
mesh-cni-ebpf-common = { path = "../mesh-cni-ebpf-common" }
mesh-cni-k8s-utils = { path = "../mesh-cni-k8s-utils" }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
cidr = { workspace = true }

[dev-dependencies]
k8s-openapi = { workspace = true, features = ["v1_34"] }

[lib]
name = "mesh_cni_vxlan_controller"
path = "src/lib.rs"
