syntax = "proto3";

package grpc.cni.v1;

service Cni {
    rpc AddVxlanPod(AddVxlanRequest) returns (AddVxlanReply) {}
    rpc AddChainedPod(AddChainedRequest) returns (AddChainedReply) {}
    rpc DeletePod(DeletePodRequest) returns (DeletePodReply) {}
}


message AddVxlanRequest {
  // Name of the pod being created
  string pod_name = 1;

  // Namespace of pod being created
  string pod_namespace = 2;

  // Determines if the CNI is configured to be chained
  bool chained = 3;

  // The host side interface index connected to the pod
  uint32 host_ifindex = 4;

}

// TODO: support ipv6
message AddVxlanReply {
  // IPv4 in bytes
  bytes ipv4 = 1;
  // Gateway for the peer device
  bytes ipv4_gateway = 2;
}

message AddChainedRequest {
  // Name of the pod being created
  string pod_name = 1;

  // Namespace of pod being created
  string pod_namespace = 2;
}

message AddChainedReply {}

message DeletePodRequest {
  // IPv4 in bytes
  repeated bytes ipv4 = 1;
}

message DeletePodReply {}
